#manifest yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api-server
  replicas: 1
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - name: api-container
          image: docker.io/arielalvarez/api:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: api-service
  name: api-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: api-server
  type: LoadBalancer