name: C

on:
  push:
    branches: [ "workflow" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Generate flex executable file
      run: |
        cd tokenizacion
        lex tokens.l
        gcc lex.yy.c -L "/usr/lib/x86_64-linux-gnu/"-lfl -o tokenizador
        mv ejemplos/ejemplo1.c  ejemplos/ejemplo1.txt
        mv ejemplos/ejemplo2.c  ejemplos/ejemplo2.txt
        echo $(./tokenizador ejemplo1.txt)
      shell: bash
