name: C

on:
  push:
    branches: [ "workflow" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Generate flex executable file
      run: |
        cd tokenizacion
        sudo apt-get install flex
        lex tokens.l
        gcc lex.yy.c -lfl -o tokenizador
      shell: bash
