name: C

on:
  push:
    branches: [ "workflow" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Generate flex executable file
      run: |
        cd tokenizacion
        lex tokens.l
        gcc lex.yy.c -L "/usr/lib/x86_64-linux-gnu/"-lfl -o tokenizador
      shell: bash
