name: C

on:
  push:
    branches: [ "workflow" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Generate flex executable file
      run: |
        cd tokenizacion
        lex tokens.l
        gcc lex.yy.c -L "/usr/lib/x86_64-linux-gnu/"-lfl -o tokenizador

      shell: bash
    - name: docker build
      run: docker build -t ${{secrets.DOCKER_USER}}/api:latest .
    - name: show images
      run: docker images
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker Push to hub.docker.com
      run: docker push ${{secrets.DOCKER_USER}}/api:latest

    - name: show deployment.yaml
      run: cat deployment.yaml
    - uses: okteto/context@2.7.0
      with:
        token: ${{secrets.OKTETO_TOKEN }}

    - name: Deploy and Wait
      uses: okteto/actions/deploy@v1
      env:
        KUBECONFIG: ${{ steps.namespace.outputs.kubeconfig }}
      with:
        namespace: arielalvarezcortez
        manifest: deployment.yaml
        tag: ${{ secrets.DOCKER_USERNAME }}/${{secrets.MODEL_NAME}}:latest

    - name: Deploy and Wait
      uses: okteto/actions/deploy@v1
      env:
        KUBECONFIG: ${{ steps.namespace.outputs.kubeconfig }}
      with:
        namespace: arielalvarezcortez
        manifest: deployment.yaml
        tag: ${{ secrets.DOCKER_USERNAME }}/api:latest
